### ISSUE TITLE
server explorer -> improvement -> show first N rows from a table by double click or somehow 

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#11]
subj 
![image](https://user-images.githubusercontent.com/1144025/94664587-bae89a00-0313-11eb-9daa-cc8191ec8980.png)

**Comment by jshinonome** [comment]
v1.8.2 includes a preview button for tables. to be released by 10/11

**Comment by jshinonome** [comment]
Released
