### ISSUE TITLE
autoscrolling-on resets to autoscrolling-off when I change focus

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#12]
![image](https://user-images.githubusercontent.com/1144025/95015298-c52cd000-0654-11eb-9ce4-769ef4959896.png)

**Comment by jshinonome** [comment]
This is a feature of vscode. There is nothing I can do about it. You need to click the last line to toggle it on.

**Comment by jshinonome** [comment]
Check this:
https://stackoverflow.com/questions/58855587/vscode-turn-auto-scrolling-permanently-on

**Comment by Igor-Mochalin** [comment]
> Check this:
> https://stackoverflow.com/questions/58855587/vscode-turn-auto-scrolling-permanently-on

looks  ok,  thanks
