### ISSUE TITLE
Timestamp of Query View is converted to local time

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#14]
Query  view( by default.) must have  the same  values and settings  as  in console 

![image](https://user-images.githubusercontent.com/1144025/95515901-07dd0800-09c7-11eb-8a50-9d4fa8613ebd.png)

**Comment by jshinonome** [comment]
The reason is that javascript doesn't have different types for numbers, so basically, all numbers returned to javascript become float. This query view is more for virtualization. To show exactly as console, need a lot of extra works. I would recommend you use the console rather than the query view.

**Comment by Igor-Mochalin** [comment]
Yes, i understand, but you will not use 'query view' in 80%of cases ... Look into the "ts" field  for example..... Time is the main parameter in q ....

**Comment by jshinonome** [comment]
Right, This is an issue with timezone. I can take a look if I can sort this out. It looks like node-q doesn't support to load ts as it is unless you set your timezone to UTC.

**Comment by jshinonome** [comment]
Change to UTC for Query View in 1.8.3

**Comment by jshinonome** [comment]
Millisecond should appear when vscode upgrade to use chrome 84.
https://www.chromestatus.com/feature/5704965743968256

**Comment by jshinonome** [comment]
add a new grid mode for the table from version 1.9.0, it can show nanosecond now.
