### ISSUE TITLE
 Query View -> wrong view  for  list of symbols 

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#15]
t2:([]dict:(`a`a1`a2`a3`a4;`b;`c))
![image](https://user-images.githubusercontent.com/1144025/95654875-b5593400-0b0b-11eb-8a6c-24bff3f4639d.png)

expected result: 
```
dict
--------------
`a`a1`a2`a3`a4
`b
`c
```

**Comment by jshinonome** [comment]
What is missing from the view? Backtick?
Symbol is convert to string in JavaScript so there won't be any backtick.

**Comment by Igor-Mochalin** [comment]
yes must be  `a`a1`a2 instead  of  a,a1,a3

**Comment by jshinonome** [comment]
From the screenshot you post here, it is a,a1,a2. What do I miss?

**Comment by jshinonome** [comment]
Sorry, I cannot tell what is different from the screenshot. Closing this.
