### ISSUE TITLE
Increase decimal digits for Query View

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#16]
Hi,  I think you need to add  new  tool for  data visualization  or  modify  Query  View  because  50% of data in Query  View  and console are different  ...  i understand that  it's by design but  not  expected ....    
I can use  console  but  in 30% cases  console  is  not  really useful  because  i  have  a lot  of  columns…..  

regarding  Query  View again  ... 
as  an  example  I can't  compare  bid ,ask, price .... 
 t:([]bid:1.443 1.443 1.443; ask: 1.447 1.448 1.446)
![image](https://user-images.githubusercontent.com/1144025/95655050-54caf680-0b0d-11eb-9e79-d0dda64bb02f.png)

**Comment by jshinonome** [comment]
Understood about your concerns. It is very hard to find a free solution to everything. If you can find a better virtualization package, I am happy to switch to that.
For the question, I will check if I can increase the precision.

**Comment by Igor-Mochalin** [comment]
yes,  i'll  take a look  .. 
in  my mind  you  must  must and  must  keep  ALL original  fields  ....  otherwise useless... or  maybe  for  managers  only  ))) not for  devs

**Comment by jshinonome** [comment]
Sorry, javascript doesn't have same type as kdb+ so I basically only use console output for dev.

**Comment by jshinonome** [comment]
Set decimal digits to 7 from 1.8.3
