### ISSUE TITLE
server list ->  wrong connection 

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#17]
i guess you are using label as unique  id  in the server list instead of tag + label...
so steps to reproduce:
I have 
TAG1 -> myLabel->localhost:1444
TAG2 -> myLabel->remote host:1444

i will always connect to same server
as workaround i can use different labels

**Comment by jshinonome** [comment]
Exactly, as you guessed. Will take a look.

**Comment by jshinonome** [comment]
Fixed in ver 1.8.5

**Comment by Flomastruk** [comment]
Just installed the extension and failed to use, the following error is displayed when attempting to connect to localhost server

connect ECONNREFUSED 127.0.0.1:1823

**Comment by jshinonome** [comment]
Did you start a process on that port(1823)? If you did start a process on that port, can you try to connect to that process from another q process and run 
```
`:localhost:1823 ".z.d"
```

**Comment by Flomastruk** [comment]
You are right, I haven't realized the connection should be open. This has fixed it, thank you!
