### ISSUE TITLE
The column type in the query result is incorrect!

### ISSUE THREAD

**Issue by trackless** [jshinonome/vscode-q#2]
The type of the 'account' column is symbol. But when the values of the 'account' column contains similar to  '100001',it will be recognized as a number.
![query](https://user-images.githubusercontent.com/1817562/89701593-f47fd300-d96a-11ea-85ce-8ab634e3e3f6.png)

**Comment by jshinonome** [comment]
Currently, it is automatically recognised, will check perspective api, see if there is a way to specified types.

**Comment by jshinonome** [comment]
This should be fixed in 1.6.9, please update your extension.
