### ISSUE TITLE
Timestamps changed to 1969.12.31D18:59:59.999 with timestamps with .999

### ISSUE THREAD

**Issue by daczar** [jshinonome/vscode-q#20]
When querying the timestamp field in table, if the timestamp value has .999 in it. 

In the q console:

q)t2:2016.01.13D17:11:29.99900 2016.01.13D17:11:29.9900 2016.01.13D17:11:29

and in VS Code:

([] time: t2)

![vscode-q-timestampissue](https://user-images.githubusercontent.com/39592322/99262668-3f23ad80-27ec-11eb-83ae-2acab4ae6e39.png)

Also when you save the table to csv the timestamp value is stored as -1

This only appears to impact the query view tab for the table.  The console view returns the timestamp correctly.

**Comment by jshinonome** [comment]
Will take a look

**Comment by jshinonome** [comment]
Looks like an issue with perspective-viewer-datagrid

**Comment by jshinonome** [comment]
https://github.com/finos/perspective/issues/1252#issue-745277445

**Comment by jshinonome** [comment]
Issus was solved in the latest perspective
