### ISSUE TITLE
Able to choose q server from keyboard

### ISSUE THREAD

**Issue by kimtang** [jshinonome/vscode-q#24]
vscode-q is cool.
Would be good to be able to choose a q server from the server list via keyboard. Be able to stay completely in the keyboard without moving the mouse would be nice.

**Comment by jshinonome** [comment]
It should be easy to add this, let me think about it.

**Comment by jshinonome** [comment]
I just released 1.9.9, you can use `ctrl+shift+p`, type *connect to q*, and choose kdb+/q ext: connect to q server.
You can also assign a shortcut for it.

**Comment by kimtang** [comment]
Many thanks for the quick implementation

**Comment by jshinonome** [comment]
You are welcome, let me know if any other requirements
