### ISSUE TITLE
Disable output console when i open a q file!

### ISSUE THREAD

**Issue by trackless** [jshinonome/vscode-q#28]
Could I have a setting option to disable output console when I open a q file?
I just edit a q file。😂️

**Comment by jshinonome** [comment]
Do you mean the q Language Server output channel?

**Comment by trackless** [comment]
> Do you mean the q Language Server output channel?

yep.

**Comment by jshinonome** [comment]
vscode didn't provide a way to turn off this channel, and I have already set the default trace level to "off".
