### ISSUE TITLE
Query view

### ISSUE THREAD

**Issue by vvishwa** [jshinonome/vscode-q#29]
I am using VS Code January 2021 (version 1.53) with vscode-q v2.1.1
I added some remote and local sever and created table, I can run query but where is "Query View" mentioned in document? It will be great if you could please mention or am I missing additional extension.

**Comment by jshinonome** [comment]
Hi please refer to readme, https://github.com/jshinonome/vscode-q#query-mode

**Comment by jshinonome** [comment]
Type ctrl+shift+p and call kdb+/q ext: Switch Query Mode
