### ISSUE TITLE
Fails to initialize language server if no permission to 'stat' folder

### ISSUE THREAD

**Issue by petesmc** [jshinonome/vscode-q#3]
Fails to initialize language server if no permission to 'stat' folder.

```
mainThreadExtensionService.ts:66 Error: Request initialize failed with message: EPERM: operation not permitted, stat 's:\afolder/hdb'
	at c:\dev\vscode_extensions\extensions\jshinonome.vscode-q-1.7.1\dist\q-ext.js:3:65923
	at c:\dev\vscode_extensions\extensions\jshinonome.vscode-q-1.7.1\dist\q-ext.js:3:66217
	at Immediate.<anonymous> (c:\dev\vscode_extensions\extensions\jshinonome.vscode-q-1.7.1\dist\q-ext.js:3:66576)
	at processImmediate (internal/timers.js:439:21)
```

**Comment by jshinonome** [comment]
can you share folder structure? where is the stat folder in your workspace? No read permission or no permission at all?

**Comment by petesmc** [comment]
Hmm this seems weirder than i would have expected. The 'stat' is the command it is trying to run. I *think* in the walkSync() function an EPERM error is thrown that needs to be caught.

- VS Code on windows
- Map linux drive is s: in windows
- Open folder s:\afolder in vscode
- afolder/hdb is a broken sym link to another dir (only valid when on specific hosts), but has correct permissions

Tried to debug this on my machine, but no access to required npm dependencies unfortunately.

**Comment by jshinonome** [comment]
Thanks for the information, I will try to reproduce this error later today. and release a fix. In the meantime, can you try to add this path to ignorePattern(https://github.com/jshinonome/vscode-q#configuration) see if it works?

**Comment by petesmc** [comment]
yes that works. 

I managed to reproduce it in a barebones script:
```
const walkSync = require('walk-sync');
const fs = require('fs');
const path = require('path');

const globsPattern = ['**/src/**/*.q'];
const ignorePattern =['**/build', '**/node_modules'];
rootPath = 'S:\\afolder';

const qSrcFiles = walkSync(rootPath, {
                directories: false,
                globs: globsPattern,
                ignore: ignorePattern
            });
```

Error:
```
S:\home\user\code\nodetest\node_modules\walk-sync\index.js:30
        throw error;
        ^

Error: EPERM: operation not permitted, stat 'S:\afolder/hdb'
    at Object.statSync (fs.js:932:3)
    at getStat (S:\home\user\code\nodetest\node_modules\walk-sync\index.js:24:19)
    at S:\home\user\code\nodetest\node_modules\walk-sync\index.js:139:25
    at Array.map (<anonymous>)
    at _walkSync (S:\home\user\code\nodetest\node_modules\walk-sync\index.js:133:31)
    at _walkSync (S:\home\user\code\nodetest\node_modules\walk-sync\index.js:154:42)
    at _walkSync (S:\home\user\code\nodetest\node_modules\walk-sync\index.js:154:42)
    at _walkSync (S:\home\user\code\nodetest\node_modules\walk-sync\index.js:154:42)
    at walkSync (S:\home\user\code\nodetest\node_modules\walk-sync\index.js:20:12)
    at Object.<anonymous> (S:\home\user\code\nodetest\app.js:14:19) {
  errno: -4048,
  syscall: 'stat',
  code: 'EPERM',
  path: 'S:\\afolder/hdb'
```

S:\afolder/hdb is a sym link to a file that does NOT have public read/write access or does not exist.

I think the error needs to be handled here but realistically i think the walk-sync module will need to handle it at the file level.

https://github.com/jshinonome/vscode-q/blob/996f78ce52076721d895e79630452834e661a396/src/server/modules/q-analyser.ts#L57

**Comment by petesmc** [comment]
Ok final comment. Found out the root cause.

s:\afolder  maps to unix drive   /home/user/afolder

Inside afolder is a sym link, but the target of the link is an **absolute** path, not relative. E.g.

```
ln -s /home/user/anewfolder/somefile hdb
```

So then when node on windows tries to stat the file, it will have some strange behavior where it throws a EPERM error instead of an ENOENT error.

Changing the absolute link to relative fixes the problem, but unfortunately this isn't something i can do in all cases. I think the error still needs to be caught and handled.

**Comment by jshinonome** [comment]
Can you try with this package 'graceful-fs'? if it works, I will take this way.
`const walkSync = require('walk-sync');
const fs = require('graceful-fs');
const path = require('path');

const globsPattern = ['**/src/**/*.q'];
const ignorePattern =['**/build', '**/node_modules'];
rootPath = 'S:\\afolder';

const qSrcFiles = walkSync(rootPath, {
                directories: false,
                globs: globsPattern,
                ignore: ignorePattern,
               fs: fs
            });`

**Comment by petesmc** [comment]
Nope doesn't fix. I think best to just catch the error and move on.

**Comment by jshinonome** [comment]
Yeah, I would want that too, this code is kind of return nothing if errors showed.
node_modules/walk-sync/index.js
May need some more time on this.
```
function getStat(path, fs) {
    try {
        return fs.statSync(path);
    }
    catch (error) {
        if (error !== null && typeof error === 'object' && (error.code === 'ENOENT' || error.code === 'ENOTDIR')) {
            return;
        }
        throw error;
    }
}
```

**Comment by petesmc** [comment]
Raised issue with walk-sync

https://github.com/joliss/node-walk-sync/issues/59

**Comment by jshinonome** [comment]
I think I found a work around and will release a fix this week.

**Comment by jshinonome** [comment]
Hello @petesmc , let me know if this is fixed in v1.7.3

**Comment by jshinonome** [comment]
Close the ticket, let me know if you still have the issue

**Comment by petesmc** [comment]
Thanks. Working well now
