### ISSUE TITLE
Highlight for attention doesn't work

### ISSUE THREAD

**Issue by BenjaminLiuPenrose** [jshinonome/vscode-q#31]
Hello, thanks so much for your work.

Recently, I tried to highlight "attention" and "todo". I followed all the steps in https://github.com/jshinonome/vscode-q#enable-highlight-for-attention-and-todo-of-comments . But apparently, red attention highlight is not working for me. 
![image](https://user-images.githubusercontent.com/24482664/111212420-f5827e00-85a5-11eb-9869-881be8b08a42.png)

Any suggestions? tyvm

**Comment by jshinonome** [comment]
There is a bug with this feature. If there is any space before `/`, it failed to recognize the token.
I will fix it.

**Comment by BenjaminLiuPenrose** [comment]
I tried reinstall vscode and it didn't work. I tried in different two windows machine. I may need other plug-in to support other textmate selector not specified in https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/themes/common/colorThemeSchema.ts#L18. Maybe vscode doesn't support `comment.line.<keyword>` syntax https://stackoverflow.com/a/46649255/14897799.
In either case, I think I should raise this issue under vscode project.

**Comment by jshinonome** [comment]
Can you try `ctrl+shift+p`, and search for "inspect token", and if you move to the line, it will show you details as below.
![image](https://user-images.githubusercontent.com/64458591/111721526-66c27980-88a3-11eb-9bdc-300da7731743.png)

**Comment by BenjaminLiuPenrose** [comment]
I see... somehow the textmate scope in my vscode is `comment.line.source.q` 
![image](https://user-images.githubusercontent.com/24482664/111843414-82e00e00-88d7-11eb-9869-80d088de8410.png)

**Comment by jshinonome** [comment]
I will release a patch 2.1.4 this weekends. Let me know if it works.
