### ISSUE TITLE
Can't add non-localhost server

### ISSUE THREAD

**Issue by milosivanovic** [jshinonome/vscode-q#32]
It seems that the newest update which changed the server create UI has a regression.

No matter what address I put in the hostname field, it always ends up creating the entry against 127.0.0.1. For example, if I choose 192.168.1.1 as the hostname and 6000 as the port, it will create it as 127.0.0.1:6000 and the connection will fail.

When I go back to re-edit, it shows a blank hostname with "localhost" as default text. I tried re-entering the hostname and then using create/update, but after submitting the issue persists and upon re-checking, the hostsname field continues to be empty.

<img width="619" alt="Screen Shot 2021-03-22 at 10 10 10 PM" src="https://user-images.githubusercontent.com/1274505/111966432-c9459f00-8b5b-11eb-9ddb-18229f3da114.png">

**Comment by jshinonome** [comment]
Sorry about the trouble, in the meantime, can you rollback to precious version? I will fix it ASAP.

**Comment by jshinonome** [comment]
Hi Milos, I have release a patch, let me know if it works.

**Comment by milosivanovic** [comment]
No trouble at all. Just wanted to give you a heads up!

I rolled back prior to submitting this issue which helped identify the regression.

Thank you for fixing!

**Comment by jshinonome** [comment]
Thank you:) 
I probably won't notice this bug for a while.
Close this ticket now. 
Do let me know if anything.
