### ISSUE TITLE
The query keeps running in vscode but it has already finished in kdb

### ISSUE THREAD

**Issue by helloyhan** [jshinonome/vscode-q#37]
When using the virtualization and run some query to show the table details, like "select from tb where date=.z.D-5", the query itself is finished in kdb, but the status still shows running in vscode side. In result, neither could I see the results of query, nor could I run other queries.

Is there a way to stop the running in vscode side? What I can do in this case is just close the vscode and restart a new one, which is quite annoying.

Thank you in advance if you can help on this issue!

**Comment by jshinonome** [comment]
Hi, are you querying too much data? vscode need to decode the binary result from kdb, so it takes a while if it is a big query.

Ctrl+Shift+p and search for "abort the query". It will abort the query.

**Comment by helloyhan** [comment]
Thanks for the prompt response!

Not always big query actually, my query that falls into this issue only results in hundreds of rows, but with tens of columns, and it did not seemingly take a while, it just blocked there.

Anyway, the ctril+shift+p works for me to cancel the query, thanks for the help!

**Comment by jshinonome** [comment]
Great. Let me know if you want me to check your data schema, I can try to reproduce on my side. I rarely see hanging query, not sure what happens.
