### ISSUE TITLE
Unable to connect to connect to q/kdb session on remote server

### ISSUE THREAD

**Issue by bobdguan** [jshinonome/vscode-q#38]
Hi Jo, 

Thanks a lot for the great extension. I installed the 2.2.4 version (the latest version that is compatible with my VS Code ver 1.56.2 Windows PC at work), all features work fine (e.g. ssh to linux box, code highlighting, editing/saving files on the linux box, etc) except for connecting to q/kdb session launched on the same remote linux box. 

I specified hostname/port/user/password in the dialogue to add server, and once I hit create, I got below error (actual contents in '[]' are omitted). 

error accepting token gss major 589824 invalid token was supplied, gss minor 0 unknown error
gss error authenticating user
a connection failed with following information `user`host`handle!([myusername];[myhost];[myhandle])

With another IDE kdbStudio, I verified that the host/port/username/password I put in are correct: if I set auth method to "username and password", I got exactly the same error as above. But if I set auth method to 'Kerberos', it connected to remote q session fine. So I was suspecting if it's the same auth method problem that caused the failure in connecting to q session with your extension. 

Could you please kindly shed some light? And if it's indeed the auth method problem, would you be able to add Kerberos as an option for auth method, so user can not only specify host/port/username/password etc but also auth method ('username & pasword' or 'Kerberos')? Many thanks!

Bob

PS: one punch man rocks!

**Comment by jshinonome** [comment]
Hi Bob,

I will try to set up kdb+ with Kerberos in my environment and test. 

In the meantime, 
- Can you provide an URL for kdbstudio if it is a open source ide?
- Would you be able the share .z.pw definition on your kdb process?

Thanks,
Jo

(Yup:) I enjoyed watching Saitama's one punch, which is  definitely a bug!!)

**Comment by bobdguan** [comment]
Thanks a lot, Jo! It would be great if you could take a look.

Here are two versions of studio for kdb+. What I'm using is probably closer
to the latter with a company plug-in for Kerberos authentication. It's
version 3.35 so probably not too different from the former (3.34) either.
For .z.pw, unfortunately I am not able to share for compliance to my
employer's policy. Hope this is okay.

https://github.com/CharlesSkelton/studio
https://github.com/finos/kdb-studio

Let me know if you need any further information. Thanks!

Bob

**Comment by bobdguan** [comment]
And really look forward to next season of one punch... been quite a while...

**Comment by jshinonome** [comment]
I have checked kdbstudio, and it looks like your company added a customized plugin for Kerberos auth. I cannot implement this unless I have a similar environment for me to test.

If you can provide me some javascript code that works on your side, I may be able to give it a try.
.e.g https://stackoverflow.com/questions/20098912/kerberos-authentication-in-node-js-https-get-or-https-request
```
const kerberos = require('kerberos').Kerberos;
const fetch = require('node-fetch');
(async () => {
    const client = await kerberos.initializeClient("HTTP@site.internal.net", {
        mechOID: kerberos.GSS_MECH_OID_SPNEGO,
    })
    // I think the ticket is something you need to use to connect to kdb proccesses. `:hostname:port:username;ticket
    const ticket = await client.step("")
})();
```

**Comment by bobdguan** [comment]
Understood, thanks. I'll try to see what I can do on my side. Regards,

Bob

**Comment by bobdguan** [comment]
Works fine now with \x .z.pw, thanks so much for the kind help!

**Comment by jshinonome** [comment]
Great, at least you have a work around for this. I will leave this open and implement it once I had access to Kerberos auth kdb processes.

**Comment by bobdguan** [comment]
Sounds great, thanks again!

I got it work with the 2.2.4, but cannot install 2.2.5, vs code complains
it's not compatible, just letting you know. But for now, I'm really happy I
can use vs code as a full fledged IDE thanks to your awesome extension!

**Comment by jshinonome** [comment]
I try to maintain it compatible with latest vscode if possible, and no new feature added after 2.2.1. There is a guidance to build a customized low version compatible extension in the readme if you are interested.

**Comment by bobdguan** [comment]
Sounds great, I'll take a look.

**Comment by jshinonome** [comment]
v2.2.7 can use customized authentication, a simple template for authentication plugin: https://github.com/jshinonome/vscode-q-auth

**Comment by bobdguan** [comment]
Thanks, Jo! I will take a look.

Bob

**Comment by jshinonome** [comment]
Hi Bob, there is a guy(who created the pull request in this repo) in your company who is working on this, once he implemented vscode-q-auth, you can get it from him.

**Comment by bobdguan** [comment]
Thanks for the reminder Jo, I will follow up with him. Regards,

Bob
