### ISSUE TITLE
Output tab autoscroll & query view location

### ISSUE THREAD

**Issue by bobdguan** [jshinonome/vscode-q#41]
Hi Jo, 

Thanks again for the continuous help. I was wondering if it makes sense to you for the below features (let me know if I missed it and it's already there). Totally open to discussion and np at all if not feasible for this extension. :)

Bob

1. Is this possible to make the output tab autoscrolled to the bottom, which is similar experience with the terminal tab? This way user won't need to scroll down to see the results. 
2. Do you think it's sensible and doable to have the query view located beneath the code editor e.g. being part of the tabs widget including output, terminal, ports and debug console? This way user can leverage the width of the screen better than having it on the right of code editor. This is especially useful when the table is wide. I thought about this from my experience with qstudio (http://www.timestored.com/qstudio/ see the picture under "query server").

**Comment by jshinonome** [comment]
Hi Bob,

Always happy to improve the extension:)
1. This one is a vscode feature. You need it turn off "smart scroll". Ctrl + comma and search for smart scroll. I will add this to readme.
2. I will take a look at this. Not sure if I can group it with output, but I definitely can make it split window vertically.

**Comment by bobdguan** [comment]
Thanks, Jo. Re: 2, if the width is going to be split between the widget holding other tabs and the query view tab, probably the value of this change is marginal given currently query view is sharing width with code editor. Appreciate taking a look into this, yet my 2 cent is, if the query view cannot be part of the widget for tabs, probably the current layout is good enough. Please kindly let me know how you think. 

On 1, I tried both smart scroll on vs off, it seems I am getting same behavior while doing below. 

1. Make sure terminal tab is in focus, In code editor, put in a line and execute it e.g. 0N!1 
2. Focus will be switched to output tab, the tab is scrolled to the bottom and result is visible
3. If you keep executing the same line for a few times, you will notice while output tab is still in focus, it's not scrolled further to the bottom as new result comes in. 

This is what I was hopeful to be modified, if it is sensible to you at all, but it's a rather minor point in case it's a pain to do so. (One additional observation which may or may not be relevant is, if you then switch to terminal tab and switch back, the output tab is scrolled to the bottom)

Thanks and have a nice weekend!

**Comment by jshinonome** [comment]
Hi Bob, after you switched off the smart scroll, did you turn on auto-scrolling?
![image](https://user-images.githubusercontent.com/64458591/124338464-1b7a6f80-dbe3-11eb-88f1-46894fd2b804.png)
As for 2, it seems that vscode doesn't have an option to merge it with widget tabs, nor split vertically...

**Comment by bobdguan** [comment]
Wow, that works! And np at all for the other one, just a thought. Thanks!

**Comment by jshinonome** [comment]
Nice, added this to the tips session of the readme. Thanks for bringing this up.

**Comment by bobdguan** [comment]
Of course, thanks for the help again!!
