### ISSUE TITLE
Missing extension ?

### ISSUE THREAD

**Issue by chriscoats** [jshinonome/vscode-q#43]
I think your recent change for customized auth requires jshinonome.vscode-q to be published to the marketplace.

When I attempt a server connection:
`Customized Auth Plug(jshinonome.vscode-q-auth) is not found or not activated yet`

**Comment by jshinonome** [comment]
Yes, I have released a version that supports customized authentication. Unless you check "Customized Authentication" on the server configuration, it shouldn't pop up this message.

**Comment by jshinonome** [comment]
FYI, this is the extension which should be implemented by yourself for a customized authentication.

https://github.com/jshinonome/vscode-q-auth

**Comment by chriscoats** [comment]
If you edit an existing server with customized authentication = false, the dialog initializes it to true which isn't obvious if you aren't looking for it.

**Comment by jshinonome** [comment]
Thanks for letting me know. Just released 2.2.8, let me know if you still see the issue.

**Comment by chriscoats** [comment]
That fixes it thanks.
