### ISSUE TITLE
Failed to find any source warning in every project

### ISSUE THREAD

**Issue by Yanpas** [jshinonome/vscode-q#44]
I get `Failed to find any source files using the glob "**/src/**/*.q,**/qcode*/**/*.q". Some feature will not be available.` warning every time I open different folders in vscode. Can this extension be silent on the projects that don't have q code?

Tip: you can set activation point to opening q-lang file instead of traversing entire project.

**Comment by jshinonome** [comment]
Oh, I didn't think through about this for last update. I may remove this warning message. Let me think about it.

**Comment by jshinonome** [comment]
Hi, this warning is moved to the q Lang Server output channel now(v2.3.2)

**Comment by Yanpas** [comment]
Thank you!
