### ISSUE TITLE
Feature request: automatic refresh of server state after Ctrl+q or Ctrl+r

### ISSUE THREAD

**Issue by travis-leith** [jshinonome/vscode-q#46]

**Comment by jshinonome** [comment]
Hi, Is "q explorer auto refresh
" the configuration you are looking for? You can set it to true and reload vscode.

**Comment by travis-leith** [comment]
I'm sorry but I cannot find this setting

![image](https://user-images.githubusercontent.com/29927084/139848270-97683249-87a4-493f-968b-f4ea87328dc7.png)

I can find a command to do the refresh on demand though

![image](https://user-images.githubusercontent.com/29927084/139848423-1a263759-999b-4aba-9762-f0fbdfff6e91.png)

**Comment by jshinonome** [comment]
What is your vscode-q version?

**Comment by travis-leith** [comment]
wow, looks like I am running an ancient version: 1.15.1, will try to get it updated and report back

**Comment by jshinonome** [comment]
This is how it looks like
![image](https://user-images.githubusercontent.com/64458591/139850169-b0edf1be-ffcf-4a86-9b10-bbc3d76d71f8.png)

**Comment by travis-leith** [comment]
After updating, I confirm everything is working as expected. Thanks.
