### ISSUE TITLE
Delay showing q Console output after executing query

### ISSUE THREAD

**Issue by milosivanovic** [jshinonome/vscode-q#49]
There seems to be a half a second delay before displaying the result of any query, even to a local q server. For example, the query might take 5ms to execute but it takes much longer to show the result in the q Console. The low responsiveness masks the visual interpretation of the responsiveness of the query, which hurts development.

Do you know if this a VS Code limitation or something that can be fixed inside the extension?

I checked https://github.com/jshinonome/vscode-q/blob/v2.3.6/src/client/modules/query-console.ts#L27 but couldn't find any artificial delay.

**Comment by jshinonome** [comment]
This is a limitation of vscode output channel. I haven't found a better to way to display q console result yet.
