### ISSUE TITLE
<go to  Definition (f12)> Unable to open <file>...

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#5]
**steps  to reproduce:**
create 2 q file:
fist.q 
  fun:{[a;b] a+b} 
second .q 
  fun[1;2]
**go to second.q  -> f12 -> all will be ok** 
**_rename  first.q -> first_renamed.q_**
go to second.q  -> f12 -> Unable to open 'first.q': Unable to read file '........first.q'

**Comment by jshinonome** [comment]
configure for each workspace is possible from 1.7.5, please refer to https://github.com/jshinonome/vscode-q#configuration
