### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by gyorokpeter** [jshinonome/vscode-q#52]
GIFs are not the best choice for presenting the functionality of the plugin in the readme. The best would be a series of screenshots, with (searchable) text in between that explains what is happening. But even an embedded video is better than a GIF because then you at least get to start/stop/rewind etc.

**Comment by jshinonome** [comment]
Made a video for this. I will update it if necessary.
https://www.youtube.com/watch?v=-k6lx5ePo70
