### ISSUE TITLE
Alternative methods for sending queries

### ISSUE THREAD

**Issue by gyorokpeter** [jshinonome/vscode-q#53]
For example in a menu when right-clicking on a server or via toolbar button(s).

For comparison, [KDB Studio](https://github.com/finos/kdb-studio) has 3 different ways to choose what to send to the server using 2 different commands:

- The selected text (even if it cuts a word in half, only the selected part is sent) – Ctrl+E with text selected
- The whole content of the editor – Ctrl+E with no text selected
- The current line, ignoring selection – Ctrl+Enter

All 3 have their uses, e.g. full text to load an entire script into an empty q process, selected text to send a multiline function, and single-line to execute simple statements as it’s easier to put the cursor just somewhere on the line than selecting the line from start to end.

**Comment by jshinonome** [comment]
@gyorokpeter I have added 3 buttons to server explorer. As for the query for full text, I would like to let users select all text first and query selection.
![image](https://user-images.githubusercontent.com/64458591/156868476-46e523ce-eded-449e-a770-82cea9aaa3b0.png)
