### ISSUE TITLE
Use env-paths module to store extension configuration

### ISSUE THREAD

**Issue by Yanpas** [jshinonome/vscode-q#56]
Currently extension uses HOME/.vscode directory. `.vscode` directory is owned by Visual Studio Code and path to this directory isn't provided by API (only `Extension.extensionUri` https://code.visualstudio.com/api/references/vscode-api#Extension). VSCode Remote SSH uses directory called `.vscode-server` by the way.

[env-paths](https://github.com/sindresorhus/env-paths) is a proper way to store some persistent settings.

**Comment by jshinonome** [comment]
What path do you proposed here?

**Comment by Yanpas** [comment]
https://github.com/sindresorhus/env-paths

For server list:
```
paths.config
Directory for config files.

macOS: ~/Library/Preferences/vscode-q-nodejs
Windows: %APPDATA%\vscode-q-nodejs\Config (for example, C:\Users\USERNAME\AppData\Roaming\vscode-q-nodejs\Config)
Linux: ~/.config/vscode-q-nodejs (or $XDG_CONFIG_HOME/vscode-q-nodejs)
```

For history:
```
paths.cache
Directory for non-essential data files.

macOS: ~/Library/Caches/vscode-q-nodejs
Windows: %LOCALAPPDATA%\vscode-q-nodejs\Cache (for example, C:\Users\USERNAME\AppData\Local\vscode-q-nodejs\Cache)
Linux: ~/.cache/vscode-q-nodejs (or $XDG_CACHE_HOME/vscode-q-nodejs)
```

**Comment by jshinonome** [comment]
Thanks for the explanation. I will check the PR and merge it.
