### ISSUE TITLE
Do not show QueryConsole when in grid or vis mode

### ISSUE THREAD

**Issue by Yanpas** [jshinonome/vscode-q#57]
Query Console doesn't show anythong useful, it only occupies half of the screen. Error should be shown using vscode notifications

**Comment by jshinonome** [comment]
I can get rid of "* row(s) returned". As for errors, it can show a stack trace, isn't it useful?
Do you mean to put the whole stack trace in the error message window?

**Comment by Yanpas** [comment]
I've opened the PR, now showing console only if console mode is active or error happened

**Comment by jshinonome** [comment]
removed rows count return, (v2.4.8)
