### ISSUE TITLE
Lower minimum supported vscode version to 1.44

### ISSUE THREAD

**Issue by Yanpas** [jshinonome/vscode-q#6]
If possible...

**Comment by jshinonome** [comment]
I created a offline package for 1.44 (https://github.com/jshinonome/vscode-q/releases/tag/1.7.4) as below, do you want to try if you can generate a package yourself?

1. git clone this repo,
2. change engine vscode in the package.json to 1.44, @types/vscode of devDependencies to 1.44
```
	"engines": {
		"vscode": "^1.44.0"
	},
...
	"devDependencies": {
		"@types/long": "^4.0.1",
		"@types/node": "^14.6.0",
		"@types/request": "^2.48.5",
		"@types/vscode": "^1.44.0",
		"@typescript-eslint/parser": "^3.9.1",
		"ts-loader": "^8.0.2",
		"typescript": "^3.9.7",
		"vscode-test": "^1.4.0",
		"webpack": "^4.44.1",
		"webpack-cli": "^3.3.12"
	},
```
3. run those commands from this repo, you will get a package for 1.44
```
npm i
npm i -g vsce
vsce package
```

**Comment by jshinonome** [comment]
Please give a try with those steps.

**Comment by Yanpas** [comment]
Works fine, thanks
