### ISSUE TITLE
Where can I find the tree-sitter grammar for q?

### ISSUE THREAD

**Issue by travis-leith** [jshinonome/vscode-q#62]
I want to try something very speculative that tree-sitter would make easier.

Basically I want to put together a custom linter that enforces some structure and naming conventions. I want to enforce the ordering of "private" functions vs "public" functions. I know q does not have these concepts but I have an idea for a linter to force some sort of sensible structure and avoid people writing code that looks like a bowl of spaghetti, which is what I am faced with right now.

Anyway, I'd like to play around with tree-sitter to help with this. Like I said, it is a very speculative idea, but if it works out and there is interest I can share a link here.

Where can I get the actual grammar specification? All I can see is [assets/tree-sitter-q.wasm](https://github.com/jshinonome/vscode-q/blob/master/assets/tree-sitter-q.wasm).

**Comment by jshinonome** [comment]
Sorry, tree-sitter-q is not an open-source project, but you can still play with https://github.com/jshinonome/vscode-q/blob/master/test/parser.js

**Comment by tankorsmash** [comment]
I was hoping to use the LSP stuff for Neovim using tree-sitter, and I don't think neovim's got WASM tree-sitter support widely available yet. The VSCode extension bit looks really nice, so thank you for putting it all together!

**Comment by jshinonome** [comment]
Here is something that may help.

https://www.npmjs.com/package/@jo.shinonome/qls

**Comment by tankorsmash** [comment]
Awesome that worked, thank you! I had to remove the console.logs on startup, but it's working. 

```
npm --global i @jo.shinonome/ql
qls --stdio # to make sure it works by seeing output
npm root -g # to find the node_modules path
nvim <that path>/@jo.shinonome/dist/qls/server.js
  :r!npx prettier %
  /console.log<cr>
  ddnddZZ
qls --stdio # to make sure it works by seeing no output
``` 
then the LSP client setup:

The docs were for nvim's builtin lsp(?) but I use coc.nvim, so I added
```json
		"q": {
			"command": "qls",
			"args": ["--stdio"],
			"filetypes": ["q"]
		},
```
 to it's config at `:CocConfig`'s `languageserver` prop.

Thanks for the quick response!
