### ISSUE TITLE
How to bulk import Q Server List? 

### ISSUE THREAD

**Issue by AndyCYao** [jshinonome/vscode-q#65]
Hi Jo, thank you for creating such a wonderful tool for Q development.

What is the file format for the import file for server import?  

![image](https://user-images.githubusercontent.com/6835537/157552869-99f04b65-3e89-4ce3-9b30-5e5956db2ead.png)

**Comment by jshinonome** [comment]
Hi @AndyCYao , thanks for using it.

Just create one server there, and export it. It is a json format file. You can use a kdb process to load it, `.j.k` to parse it. Then you can just update it like a table in q. Finally, you save it as a json file use `.j.j` and import it.

**Comment by AndyCYao** [comment]
Thanks so much!
