### ISSUE TITLE
Always include a closing double quote for truncated long strings in output.

### ISSUE THREAD

**Issue by travis-leith** [jshinonome/vscode-q#67]
Currently, outputting a long string that has been truncated means that whatever gets outputted after is assumed to be a string, since no closing double quote has happened yet.
Alternatively, instead of including a closing double quote, reset the state after each evaluation such that the output window does not assume it is still in the middle of a string.

To reproduce, evaluate `"." sv string til 1000`

**Comment by jshinonome** [comment]
Just released v2.5.4, let me know if it works.

**Comment by travis-leith** [comment]
Working, thanks.
