### ISSUE TITLE
Query view doesn't play will with light theme

### ISSUE THREAD

**Issue by Yanpas** [jshinonome/vscode-q#7]

**Comment by jshinonome** [comment]
Did you set 'q-ext.qview.theme' to 'light'? https://github.com/jshinonome/vscode-q#configuration
Do you mean light theme for vscode or light theme for query view?
What theme do you use, and how it looks? can you attach a screenshot too?

**Comment by Yanpas** [comment]
Didn't know about this setting. It's possible to achieve without setting and whole ide reload, just with plain css , e.g. `body.vscode-light`

https://code.visualstudio.com/api/extension-guides/webview

**Comment by jshinonome** [comment]
This setting doesn't require to reload, but at least you need to close the current query view.

**Comment by jshinonome** [comment]
Will use window.activeColorTheme to switch the theme for query view.
