### ISSUE TITLE
vscode intermittently freezes and terminates [Version: 1.67.2]

### ISSUE THREAD

**Issue by mmckenna50** [jshinonome/vscode-q#71]
When running the latest version of vscode with this extension enabled, it will often freeze when opening a q code file. When this happens, it will start to consume a lot more memory, then ultimately crash.

The issue appears to be related to the use of a newly deprecated `Buffer()` method in vscode. 

https://github.com/microsoft/vscode/issues/143535

**Comment by jshinonome** [comment]
Could be this issue?
https://github.com/jshinonome/vscode-q/issues/70

**Comment by mmckenna50** [comment]
Yes, I think this temporary fix does improve things. I guess the buffer errors were just a red herring.

Thanks Jo.

**Comment by jshinonome** [comment]
You are welcome. Closing this ticket.
