### ISSUE TITLE
Something weird about empty keyed tables

### ISSUE THREAD

**Issue by travis-leith** [jshinonome/vscode-q#74]
Empty keyed tables with a single key column are displayed as an empty dictionary. This isn't really a problem since no-one wants to look at an empty table other than to confirm it is empty. I only mention it because it might be a clue to the following problem.

Evaluating this in the console gives the expected output

```q
q)([a:`$();b:`$()] c:`$())
a b| c
---| -
```

but evaluating it from vscode gives a length error

```q
>>> -localhost-8080 @ 8:36:02 AM ---- 13(ms) elapsed
<<< query  >>>
([a:`$();b:`$()] c:`$())

<<< result >>>
>>> ERROR: length
>>> Explanation: Arguments do not conform
<<<
```

**Comment by jshinonome** [comment]
It seems to work on my side
```
>>> dev--1800 @ 12:54:02 PM ---- 0(ms) elapsed <<<
<<< query  >>>
([a:`$();b:`$()] c:`$())

<<< result >>>
a b| c
---| -
<<<
```

what are your kdb, vscode, and vscode version?

**Comment by travis-leith** [comment]
vscode: 1.67.2
vscode-q: 2.5.8

```
q).z.K
4f
q).z.k
2021.12.07
q)
```

I am using q cloud edition (qce), but apparently this is just q with some extra stuff. No changes to q itself.

**Comment by jshinonome** [comment]
could you try to debug with this query? I also use kdb 4.0 but 2021.11.04. 
```q
("{{-105!(x;enlist y;{`t`r!(0b;\"ERROR\n\",x,\"\n\",.Q.sbt@(-3)_y)})}[{`t`r!(0b;.Q.S[100 250;0j;value x])};x]}";"([a:`$();b:`$()] c:`$())")
```

**Comment by travis-leith** [comment]
more than happy to do what I can to help. Bear in mind I am kind of new to q. Do you want me to paste that query in the console? Doing so gives
```

q)("{{-105!(x;enlist y;{`t`r!(0b;\"ERROR\n\",x,\"\n\",.Q.sbt@(-3)_y)})}[{`t`r!(0b;.Q.S[100 250;0j;value x])};x]}";"([a:`$();b:`$()] c:`$())")
"{{-105!(x;enlist y;{`t`r!(0b;\"ERROR\n\",x,\"\n\",.Q.sbt@(-3)_y)})}[{`t`r!(0..
"([a:`$();b:`$()] c:`$())"
```

**Comment by jshinonome** [comment]
add a value to the start
```q
value ("{{-105!(x;enlist y;{`t`r!(0b;\"ERROR\n\",x,\"\n\",.Q.sbt@(-3)_y)})}[{`t`r!(0b;.Q.S[100 250;0j;value x])};x]}";"([a:`$();b:`$()] c:`$())")
```

**Comment by travis-leith** [comment]
```
q)value ("{{-105!(x;enlist y;{`t`r!(0b;\"ERROR\n\",x,\"\n\",.Q.sbt@(-3)_y)})}[{`t`r!(0b;.Q.S[100 250;0j;value x])};x]}";"([a:`$();b:`$()] c:`$())")
t| 0b
r| ("a b| c";"---| -")
```

**Comment by jshinonome** [comment]
looks like it works.
Let us try
```q
\e 1
.z.pg:{show x;value}
```
then run the query from vscode
```
([a:`$();b:`$()] c:`$())
```

**Comment by travis-leith** [comment]
```q
q)
"{{-105!(x;enlist y;{`t`r!(0b;\"ERROR\n\",x,\"\n\",.Q.sbt@(-3)_y)})}[{res:val..
"([a:`$();b:`$()] c:`$())"
```

**Comment by jshinonome** [comment]
but you still get `Length` error on the vscode side?

**Comment by travis-leith** [comment]
no output on the vscode side at all. Should it be `.z.pg:{show x;value x}`?

**Comment by jshinonome** [comment]
sorry I missed the last x

**Comment by travis-leith** [comment]
```q
>>> -localhost-8080 @ 9:34:08 AM ---- 1(ms) elapsed
<<< query  >>>
([a:`$();b:`$()] c:`$())

<<< result >>>
>>> ERROR: length
>>> Explanation: Arguments do not conform
>>>
  [3]  
                not 99h=type res;:`t`r!(0b;.Q.S[36 180;0j;res]);
                not (`output in key res);;
                             ^
                not 99h=type res`output;;
<<<
```

**Comment by jshinonome** [comment]
Thank you, I can see the same error. This happens when using q grid/view mode. I will take a look.

**Comment by jshinonome** [comment]
just released v2.5.9 to fix this issue. Let me know if it works.

**Comment by travis-leith** [comment]
When shall I expect it to show up here: https://marketplace.visualstudio.com/items?itemName=jshinonome.vscode-q

**Comment by jshinonome** [comment]
In a few minutes.

**Comment by travis-leith** [comment]
Fix is confirmed, thank you!
