### ISSUE TITLE
The server list doesn't work as expected

### ISSUE THREAD

**Issue by helloyhan** [jshinonome/vscode-q#75]
hello, 

I loaded the server list, it can connect to the server by just clicking on it( I see the server explorer shows the function lists ), but when I run some command in the editor via crtl+q or +enter, it still requires the connection string. Would you mind any hints? 

Thank you!

**Comment by jshinonome** [comment]
Hi, what version of vscode-q do you use?

**Comment by jshinonome** [comment]
Did you install other kdb+/q extension as well?

**Comment by helloyhan** [comment]
Ah yes, I also installed the extension vscode-kdb-q from xiaozu, that causes the conflict, it is resolved after I removed that one.

Thanks very much for ur prompt reply!!
