### ISSUE TITLE
"Enable TLS" is lost when exporting and then re-importing server list

### ISSUE THREAD

**Issue by StephaneDautroy** [jshinonome/vscode-q#77]
"Enable TLS" is lost when exporting and then re-importing server list.
Workaround: re-enable TLS manually one by one on all server entries.

**Comment by jshinonome** [comment]
Thanks for raising this, I will fix it soon.

**Comment by jshinonome** [comment]
@StephaneDautroy I have made a release v2.6.1, let me know if it works

**Comment by StephaneDautroy** [comment]
It works, thanks @jshinonome for the quick turnaround. It is very appreciated !

**Comment by jshinonome** [comment]
You are welcome!
