### ISSUE TITLE
Unable to fetch variables 2.2.5 to 2.2.6

### ISSUE THREAD

**Issue by erichards97** [jshinonome/vscode-q#78]
The extension works fine on v2.2.5 but breaks on v2.2.6 with "Unable to fetch variables" when connecting to a server.
Running KDB+ 4.0 cloud.

The change [here ](https://github.com/jshinonome/vscode-q/compare/v2.2.5...v2.2.6) of q-dict.ts on line 112 seems to be responsible. I can see the query-variable function has changed a bit since this version, and has been moved to [a separate file](https://github.com/jshinonome/vscode-q/blob/master/assets/source/query-server-variables.q).

Running the latest version of this function gives the error:
`ERROR: '.s.d0.. 
(attempt to use variable .s.d0.. without defining/assigning first (or user-defined signal))
`

Running the latest version of the function, but swapping out the change made between v2.2.5 and v2.2.6 works fine:
```
variableFn:{[excludedNamespaces]
    r: flip `n`p!"SS"$\:();
    f: {sv[`]each x,'y};
    n: f[`] (key `)except excludedNamespaces;
    v: key `.;
    r: r upsert (v,'`.);
    r: r upsert (n,'`root);
    r: r upsert (,/) {if[11h=type n:key x;r:(y[x] n), 'x];if[count r;r,:(,/).z.s[;y]each r[;0]];:r}[;f] each n;
    /BAD r: r upsert (,/){if[((::)~first value x)&11h=type n:key x;r:(y[x] n), 'x];if[count r;r,:(,/).z.s[;y]each r[;0]];:r}[;f] each n;
    r: update t:{@[{type value x};x;-255h]} each n from r;
    r: select from r where not t in 101 -255h;
    r: update b: {string value x} each n from r where t within 100 111h;
    r: update t: {$[.Q.qt value x;98h;99h]} each n from r where t in 98 99h;
    r: update m: {@[cols;x;{x}]} each n from r where t=98h;
    r: update skip:1b from r where t within 100 111h;
    r: update skip:{(::)~first value x} each n from r where t=99h;
    r: update skip:0b, pt:0b from r where t=98h;
    if[`pt in key `.Q; r: update skip:1b, pt:1b from r where n in .Q.pt];
    r: update b: {.Q.s value x} each n from r where not skip;
    r: delete skip from r;
    (`n xasc select from r where p=`root) uj `p`n xasc select from r where p<>`root
 }

variableFn[`q`Q`h`j`o]
```

Thank you

**Comment by jshinonome** [comment]
Hi, thank you for providing details. Could you try excluding namespace s?
```q
variableFn[`q`Q`h`j`o`s]
```
Let me know if you still see the error?

Also trap this error and show me the backtrace
```
.Q.trp[variableFn;`q`Q`h`j`o`s;{"error: ",x,"\nbacktrace:\n",.Q.sbt y;-1}]
```

**Comment by erichards97** [comment]
Excluding namespace s works, and in v2.6.1 of the extension as well 👍 

The trap (when s isn't excluded) returns -1j

**Comment by jshinonome** [comment]
I will exclude s namespace in default in the next release.

Could you check if this is defined on the server side?

```
.s.d0[`.]
```

**Comment by erichards97** [comment]
Thank you!
```
.s.d0[`.]
```
executes fine with no return.

**Comment by jshinonome** [comment]
I see, this caused `value` failed.

**Comment by jshinonome** [comment]
Hey, I have made a release(v2.6.3) that exclude s namespace in default and trap this kind of error as well. Let me know if it works.

**Comment by erichards97** [comment]
How do I download v2.6.3 sorry? Not seeing it on the marketplace

**Comment by jshinonome** [comment]
Oh, sorry. It is 2.6.2.

**Comment by erichards97** [comment]
v2.6.2 works 🥳 Thank you!

Funnily enough, just before updating, I found another process that doesn't work even with "s" excluded. This isn't an issue with v2.6.2 presumably due to the trap, but if you're interested I can see where it fails. Otherwise happy to leave it.
