### ISSUE TITLE
new version gives error trying to connect: self signed certificate in certificate chain.

### ISSUE THREAD

**Issue by travis-leith** [jshinonome/vscode-q#81]
I just updated vscode and vscode-q. 
Immediately prior to the update I could connect to an SSL only process.
Now I get the error "self signed certificate in certificate chain".
Any ideas?

**Comment by travis-leith** [comment]
vscode-q version 3.0.2

**Comment by travis-leith** [comment]
rolled vscode-q back to 2.65 and I can connect again. Haven't tried any other version in between. Happy to do so if you think this will be useful.

**Comment by jshinonome** [comment]
What about 3.0.0?

**Comment by travis-leith** [comment]
Both 3.0.0 and 3.0.1 work fine. Only problem is 3.0.2

**Comment by jshinonome** [comment]
Understood, I will take a look this week.

**Comment by travis-leith** [comment]
might be relevent: https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain

**Comment by jshinonome** [comment]
released v3.0.3, let me know if it fixes the issue

**Comment by travis-leith** [comment]
same error

**Comment by jshinonome** [comment]
Could you try again with v3.0.4?

**Comment by travis-leith** [comment]
Yes, that works! Out of curiosity, which change fixed it?

**Comment by jshinonome** [comment]
I needed to update node-q source file index.js to include `rejectUnauthorized: false` before initializing tls connection.
