### ISSUE TITLE
Is there a way to show the full string from the console?

### ISSUE THREAD

**Issue by horacehylee** [jshinonome/vscode-q#83]
Currently when querying for a long string, the console just truncate it around 70 chars with "..".

Is there a way to turn it off? Or extend the length of the string visible?

Tried with `\c 150 300` but the String is still truncated around 70 chars.

**Comment by jshinonome** [comment]
Hi did you try to change console size of vscode-q?
Ctrl+,(comma) and search for "Console Size for Output".

**Comment by jshinonome** [comment]
This should be controlled by \c

After you set \c, did you confirm that the \c is changed?

**Comment by horacehylee** [comment]
you are right, did the \c and now more chars is visible now.

May be the \c got reset after jumping to different connections
