### ISSUE TITLE
server exporer fails when the server contains a specific value

### ISSUE THREAD

**Issue by derekwisong** [jshinonome/vscode-q#84]
Hi Jo,

If the server contains:

```
.core.projnull: enlist first 1_(value (;));
```

which looks like `(::)` but isnt...

the lambda you use to crawl the server fails...

```
q)f
"{[excludedNamespaces]\n    r: flip `n`p!\"SS\"$\\:();\n    f: {sv[`]each x,'..
q)value f
'type
  [6]  {
        if[(@[(::)~first value@;x;{0b}])&11h=type n:key x;r:(y[x] n), 'x];
                                        ^
        if[count r;r,:(,/).z.s[;y]each r[;0]];:r
q))x
`.core.projnull
q))0N! .core.projnull;
,::
q))@[(::)~first value@;x;{0b}]
~[::;]
q))/ this is not what you expected to find...
```

You can see it looks like the identity/unary null `(::)` ... but it isnt..

```
q))value x
::
q))type value x
0h

q))(::) ~ value x
0b
```

Perhaps you should skip items that raise errors...

Regards,
Derek

**Comment by jshinonome** [comment]
Thanks for raising this, Derek. I will take a look this week.

**Comment by derekwisong** [comment]
This particular item, is a bit of a q/kdb curiosity.  It is used to create projections for use in parse trees... It also has some very peculiar properties...

I made a small mistake above, it looks like the `enlist`ed identity `::`... but isnt...

```
q)enlist[::] ~ .core.projnull
1b
``

Even though q says they are the same... they are not...

```
q)f:{x-y};
q)eval ((f;.core.projnull;10); 100)     / creating projection f[;10] with a parse tree
90
q)eval ((f;enlist[::];10); 100)    / not quite the same as with enlist ::
'type
  [1]  f:{x-y}
           ^
q))
```

**Comment by jshinonome** [comment]
Published 3.1.1, give it a try in 15 mins and let me know if it is fixed.

**Comment by derekwisong** [comment]
Thanks!  I wont be able to test it immediately at work where I'm actually having the problem (end users get updates via an internally managed mirror that gets updates on some unknown-to-me cadence).  I should get it here in a few days.

But, I will test it at home tomorrow.

Thanks again Jo!

**Comment by jshinonome** [comment]
You are welcome :)

**Comment by derekwisong** [comment]
The admins must have been smiling on me. The update happened, and i see that the server explorer now works (and has an entry for `.core.projnull`)!

Thanks @jshinonome

**Comment by jshinonome** [comment]
No problem. Happy that it works :)
