### ISSUE TITLE
Go to definition/references not working

### ISSUE THREAD

**Issue by helloyhan** [jshinonome/vscode-q#85]
Hi, this functionality doesn't work, how can I enable it again? 
A lot of functions are defined using multiple namespaces like ".a.b.c:{xxxx}", will this be the issue?

**Comment by jshinonome** [comment]
Hi, using multiple namespaces won't be an issue. What version of vscode-q do you use? In default, it only looks up source code in src folder.

**Comment by jshinonome** [comment]
If no further details provided, going to close this issue.
