### ISSUE TITLE
No way to close the Connect to a q process popup

### ISSUE THREAD

**Issue by EugeneKallis** [jshinonome/vscode-q#89]
Sometimes i hit Ctrl+Enter which will try to run a command on connected q process. If theres no q process connected the Prompt to "Connect to a q process" will come up and wont go away until i select a process. Is there a way to close this prompt because i hit the key sometimes without meaning to and i dont want to run certain commands on a q process.

**Comment by EugeneKallis** [comment]
I want to add it doesnt even let me type anything in the box, it feels as if its on a loop to keep opening that box every couple miliseconds, if i try typing something in the box it gets removed
![image](https://github.com/jshinonome/vscode-q/assets/47543292/a4d78a6e-7e61-4621-99a1-6c521906c00e)

**Comment by jshinonome** [comment]
Thanks for bringing this up. I am on leaves, so I will probably take a look this Sunday.

**Comment by EugeneKallis** [comment]
Thank you! Appreciate it, let me know if you need me to do anything

**Comment by jshinonome** [comment]
I think I have resolved this issue on vscode-k-pro not vscode-q. All latest bug fixes and features will go to vscode-k-pro, since you raise up the issue here, I will fix it.

**Comment by jshinonome** [comment]
made it to retry only once.

**Comment by EugeneKallis** [comment]
Appreciate it! thank you
