### ISSUE TITLE
Query view is empty

### ISSUE THREAD

**Issue by Igor-Mochalin** [jshinonome/vscode-q#9]
**t:([]a:1 2 3 4 5; b:`a1`a1`a3`a4`a4)**
**t -**> click Ctrl+Q here  -> Query view will be empty 
![image](https://user-images.githubusercontent.com/1144025/94663208-0ef27f00-0312-11eb-9629-b9dc142aee2b.png)

**Comment by jshinonome** [comment]
Does it never show or just for the first time? For the first time, it can fail to show because it is loading the web view.

**Comment by Igor-Mochalin** [comment]
![image](https://user-images.githubusercontent.com/1144025/94665389-bec8ec00-0314-11eb-9384-c9404e4aab9e.png)

**Comment by jshinonome** [comment]
The data disappeared when lost focus on Query View. I will check if I can solve this.

**Comment by jshinonome** [comment]
Released 1.8.1 for this issue
