### ISSUE TITLE
exporting from visualization tool: copying as .png

### ISSUE THREAD

**Issue by rdffy** [jshinonome/vscode-q#93]
When copying as .png the bottom left corner of the graph has the axis labels  cut off.

The x axis with times has the first time (which is directly below the y axis) cut in half. 09:30 becomes :30
The same happens on the y axis except the first label is split horizontally rather than vertically.

**Comment by jshinonome** [comment]
Again, I have no intention of upgrading the visualization package(perspectives) for vscode-q
