### ISSUE TITLE
Visualization tool request: adjustable precision on axis and variable amount of source data for graph 

### ISSUE THREAD

**Issue by rdffy** [jshinonome/vscode-q#95]
1.  axis precision
We haven't found a way to set the axis to have say, 3 decimal point precision vs the default 2. This is very helpful when dealing with quite small floats and reals. Otherwise you have duplicate axis labels which do represent different values but due to the 2 decimal place limit the labels match. 

2. Source data for visualization
When taking in a table sand graphing it there seems to be a limit of 1000 rows.  Can this be made configurable?

**Comment by jshinonome** [comment]
1. Dependencies for vscode-q are a bit outdated now, and I am less likely to upgrade, considering it is in maintenance mode. New features will only be implemented in the paid plug-in, vscode-k-pro.
2. Yes, not configurable, but you can remove the limit, ctrl+shift+p, and call `kdb+/q ext: Toggle Unlimited Query`
