### ISSUE TITLE
Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by ronnieqt** [jshinonome/vscode-q#96]
Hi Community,

When trying to type and save the following code in tmp.q

```q
my_func: {
  if[1b; d[`abc]: select col1 from t];
  }
```

The following error shows up:

```
Request textDocument/documentSymbol failed.
Error: name must not be falsy 
```

Please note that the above code is meaningless; I am trying to simplify the context here.

Would you please help check and suggest how to avoid this? Thanks.

**Comment by jshinonome** [comment]
Hi Ronnie, thanks for bringing this up. I have made a release 3.2.1, could you please give it a try and let me know if it works?

**Comment by ronnieqt** [comment]
Hi @jshinonome, thanks for the quick response. It works perfectly now!

**Comment by jshinonome** [comment]
Cool, thanks for the confirmation.
